// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: audio_mixer

#include "../ui.h"


// IMAGE DATA: assets/audio_wave_1.png
   const char *ui_img_audio_wave_1_png = "S:assets/audio_wave_1.png";
