// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: audio_mixer

#include "../ui.h"


// IMAGE DATA: assets/indicator_ver.png
   const char *ui_img_indicator_ver_png = "S:assets/indicator_ver.png";
