// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: audio_mixer

#include "../ui.h"


// IMAGE DATA: assets/pot_ver_line.png
   const char *ui_img_pot_ver_line_png = "S:assets/pot_ver_line.png";
