// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: audio_mixer

#include "../ui.h"


// IMAGE DATA: assets/btn_1_inact.png
   const char *ui_img_btn_1_inact_png = "S:assets/btn_1_inact.png";
