// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: audio_mixer

#include "../ui.h"


// IMAGE DATA: assets/btn_eq_act.png
   const char *ui_img_btn_eq_act_png = "S:assets/btn_eq_act.png";
