// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project_stm32

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_lTime;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_timel;
extern lv_obj_t *ui_lCpu;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Image1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

